<?php

if (!defined('ABSPATH')) {
    exit;
}

if (!function_exists('mzf_get_form_post_type_definition')) {
    function mzf_get_form_post_type_definition(): array
    {
        return [
            'key' => 'post_type_69ad51e3166cc',
            'title' => 'Forms',
            'menu_order' => 0,
            'active' => true,
            'post_type' => 'form',
            'advanced_configuration' => true,
            'import_source' => '',
            'import_date' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
            'labels' => [
                'name' => 'Forms',
                'singular_name' => 'Form',
                'menu_name' => 'Forms',
                'all_items' => 'All Forms',
                'edit_item' => 'Edit Form',
                'view_item' => 'View Form',
                'view_items' => 'View Forms',
                'add_new_item' => 'Add New Form',
                'add_new' => 'Add New Form',
                'new_item' => 'New Form',
                'parent_item_colon' => 'Parent Form:',
                'search_items' => 'Search Forms',
                'not_found' => 'No forms found',
                'not_found_in_trash' => 'No forms found in Trash',
                'archives' => 'Form Archives',
                'attributes' => 'Form Attributes',
                'featured_image' => '',
                'set_featured_image' => '',
                'remove_featured_image' => '',
                'use_featured_image' => '',
                'insert_into_item' => 'Insert into form',
                'uploaded_to_this_item' => 'Uploaded to this form',
                'filter_items_list' => 'Filter forms list',
                'filter_by_date' => 'Filter forms by date',
                'items_list_navigation' => 'Forms list navigation',
                'items_list' => 'Forms list',
                'item_published' => 'Form published.',
                'item_published_privately' => 'Form published privately.',
                'item_reverted_to_draft' => 'Form reverted to draft.',
                'item_scheduled' => 'Form scheduled.',
                'item_updated' => 'Form updated.',
                'item_link' => 'Form Link',
                'item_link_description' => 'A link to a form.',
            ],
            'description' => 'Manage reusable form definitions used for contact, quote, upload, and other lead-capture workflows.',
            'public' => true,
            'hierarchical' => false,
            'exclude_from_search' => true,
            'publicly_queryable' => false,
            'show_ui' => true,
            'show_in_menu' => true,
            'admin_menu_parent' => '',
            'show_in_admin_bar' => true,
            'show_in_nav_menus' => false,
            'show_in_rest' => true,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Posts_Controller',
            'menu_position' => '',
            'menu_icon' => [
                'type' => 'dashicons',
                'value' => 'dashicons-editor-table',
            ],
            'rename_capabilities' => false,
            'singular_capability_name' => 'post',
            'plural_capability_name' => 'posts',
            'supports' => [
                'title',
                'page-attributes',
                'custom-fields',
            ],
            'taxonomies' => '',
            'has_archive' => false,
            'has_archive_slug' => '',
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'post_type_key',
            'query_var_name' => '',
            'can_export' => true,
            'delete_with_user' => false,
            'register_meta_box_cb' => '',
            'enter_title_here' => '',
        ];
    }
}

if (!function_exists('mzf_get_form_post_type_args')) {
    function mzf_get_form_post_type_args(): array
    {
        $definition = mzf_get_form_post_type_definition();

        return [
            'labels' => $definition['labels'],
            'description' => $definition['description'],
            'public' => (bool) $definition['public'],
            'hierarchical' => (bool) $definition['hierarchical'],
            'exclude_from_search' => (bool) $definition['exclude_from_search'],
            'publicly_queryable' => (bool) $definition['publicly_queryable'],
            'show_ui' => (bool) $definition['show_ui'],
            'show_in_menu' => (bool) $definition['show_in_menu'],
            'show_in_admin_bar' => (bool) $definition['show_in_admin_bar'],
            'show_in_nav_menus' => (bool) $definition['show_in_nav_menus'],
            'show_in_rest' => (bool) $definition['show_in_rest'],
            'rest_namespace' => (string) $definition['rest_namespace'],
            'rest_controller_class' => (string) $definition['rest_controller_class'],
            'menu_icon' => (string) ($definition['menu_icon']['value'] ?? 'dashicons-editor-table'),
            'supports' => (array) $definition['supports'],
            'has_archive' => false,
            'rewrite' => false,
            'query_var' => false,
            'can_export' => (bool) $definition['can_export'],
            'delete_with_user' => (bool) $definition['delete_with_user'],
            'map_meta_cap' => true,
        ];
    }
}

if (!function_exists('mzf_register_form_post_type_fallback')) {
    function mzf_register_form_post_type_fallback(): void
    {
        if (post_type_exists('form')) {
            return;
        }

        register_post_type('form', mzf_get_form_post_type_args());
    }
}
add_action('init', 'mzf_register_form_post_type_fallback', 1);

if (!function_exists('mzf_get_form_field_group_definition')) {
    function mzf_get_form_field_group_definition(): array
    {
        return [
            'key' => 'group_69ad52c00ded6',
            'title' => 'Form',
            'fields' => [
                [
                    'key' => 'field_69ad538cd2984',
                    'label' => 'Button Text',
                    'name' => 'button_text',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'layout' => 'block',
                    'sub_fields' => [
                        [
                            'key' => 'field_69ad52c1d297f',
                            'label' => 'Submit Text',
                            'name' => 'submit',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => 'Send your message',
                            'maxlength' => '',
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ],
                        [
                            'key' => 'field_69ad5313d2980',
                            'label' => 'Sending Text',
                            'name' => 'sending',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => 'Sending your message',
                            'maxlength' => '',
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ],
                        [
                            'key' => 'field_69ad532fd2981',
                            'label' => 'Sent Text',
                            'name' => 'sent',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => 'Message sent!',
                            'maxlength' => '',
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ],
                    ],
                ],
                [
                    'key' => 'field_69ad550cd2989',
                    'label' => 'Messages',
                    'name' => 'messages',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'layout' => 'block',
                    'sub_fields' => [
                        [
                            'key' => 'field_69ad550cd298d',
                            'label' => 'Success Message',
                            'name' => 'success',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => 'Your message was sent successfully. We will be in touch with you shortly.',
                            'allow_in_bindings' => 0,
                            'tabs' => 'visual',
                            'toolbar' => 'basic',
                            'media_upload' => 0,
                            'delay' => 0,
                        ],
                        [
                            'key' => 'field_69ad550cd298e',
                            'label' => 'Error Message',
                            'name' => 'error',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => 'Your message failed to send. Refresh the page and try again. If the issue persists, please give us a call or send us an email so we can take care of your request.',
                            'allow_in_bindings' => 0,
                            'tabs' => 'visual',
                            'toolbar' => 'basic',
                            'media_upload' => 0,
                            'delay' => 0,
                        ],
                    ],
                ],
                [
                    'key' => 'field_69ad53e7d2985',
                    'label' => 'User Email',
                    'name' => 'email_user',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'layout' => 'block',
                    'sub_fields' => [
                        [
                            'key' => 'field_69ad54e8d2988',
                            'label' => 'Subject',
                            'name' => 'subject',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => 'Thank you for your request!',
                            'maxlength' => '',
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ],
                        [
                            'key' => 'field_69ad557bd298f',
                            'label' => 'Intro',
                            'name' => 'intro',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => 'Hey',
                            'maxlength' => '',
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ],
                        [
                            'key' => 'field_69ad558cd2990',
                            'label' => 'Body',
                            'name' => 'body',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => 'We have received your message and will follow up shortly.',
                            'allow_in_bindings' => 0,
                            'tabs' => 'visual',
                            'toolbar' => 'basic',
                            'media_upload' => 0,
                            'delay' => 0,
                        ],
                        [
                            'key' => 'field_69ad55c0d2991',
                            'label' => 'Salutation',
                            'name' => 'salutation',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => 'Sincerely,',
                            'maxlength' => '',
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ],
                        [
                            'key' => 'field_69ad55dfd2992',
                            'label' => 'Signature',
                            'name' => 'signature',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => '',
                            'maxlength' => '',
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ],
                    ],
                ],
                [
                    'key' => 'field_69ad5755a1ddf',
                    'label' => 'Admin Email',
                    'name' => 'email_admin',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'layout' => 'block',
                    'sub_fields' => [
                        [
                            'key' => 'field_69ad55fed2993',
                            'label' => 'Recipients',
                            'name' => 'recipients',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => 'Separate multiple emails with a semi-colon. If left empty, the website email is used instead.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => '',
                            'maxlength' => '',
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ],
                    ],
                ],
                [
                    'key' => 'field_69ad5644d2994',
                    'label' => 'Disclaimer',
                    'name' => 'disclaimer',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => 'By submitting this form, you agree to our <a href="/privacy-policy" target="_blank">Privacy Policy.</a>',
                    'allow_in_bindings' => 0,
                    'tabs' => 'visual',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 0,
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'form',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
            'display_title' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
        ];
    }
}

if (!function_exists('mzf_register_acf_form_definitions')) {
    function mzf_register_acf_form_definitions(): void
    {
        if (function_exists('acf_add_local_internal_post_type')) {
            acf_add_local_internal_post_type(mzf_get_form_post_type_definition(), 'acf-post-type');
        }

        if (function_exists('acf_add_local_field_group')) {
            acf_add_local_field_group(mzf_get_form_field_group_definition());
        }
    }
}
add_action('acf/init', 'mzf_register_acf_form_definitions', 5);
