<?php

    function meza_get_business_information_branding_fields(): array
    {
        return [
            [
                'key' => 'field_meza_business_site_logo',
                'label' => 'Site Logo',
                'name' => 'wp_site_logo',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => 'Appears in the header, login screen, and email templates. Upload a transparent version when possible.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'return_format' => 'id',
                'library' => 'all',
                'preview_size' => 'meza_branding_preview',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'allow_in_bindings' => 0,
            ],
            [
                'key' => 'field_meza_business_site_logo_alt',
                'label' => 'Site Logo (Alternative)',
                'name' => 'wp_site_logo_alternative',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => 'Appears in the footer and other dark sections. Upload a transparent version when possible.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'return_format' => 'id',
                'library' => 'all',
                'preview_size' => 'meza_branding_preview',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'allow_in_bindings' => 0,
            ],
            [
                'key' => 'field_meza_business_site_icon',
                'label' => 'Site Icon',
                'name' => 'wp_site_icon',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => 'Used in browser tabs, bookmark bars, and mobile apps. Upload a square image that is at least 512 by 512 pixels.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'return_format' => 'id',
                'library' => 'all',
                'preview_size' => 'meza_branding_preview',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'allow_in_bindings' => 0,
            ],
            [
                'key' => 'field_meza_business_theme_thumbnail',
                'label' => 'Theme Thumbnail',
                'name' => 'wp_theme_thumbnail',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => 'Used by WordPress to represent the website. Upload a 4:3 image that is at least 1200 by 900 pixels.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'return_format' => 'id',
                'library' => 'all',
                'preview_size' => 'meza_theme_thumbnail_preview',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => 'png,gif,jpg,jpeg,webp,avif',
                'allow_in_bindings' => 0,
            ],
            [
                'key' => 'field_meza_business_social_share_default',
                'label' => 'Social Share Default',
                'name' => 'wp_social_share_default',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => 'Used when a page or post does not have its own share image. Defaults to the Theme Thumbnail until you choose a replacement.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'return_format' => 'id',
                'library' => 'all',
                'preview_size' => 'meza_theme_thumbnail_preview',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => 'png,gif,jpg,jpeg,webp,avif',
                'allow_in_bindings' => 0,
            ],
        ];
    }

    function meza_get_crm_integration_fields(): array
    {
        return [
            [
                'key' => 'field_69b5b54f29383',
                'label' => 'Platform',
                'name' => 'platform',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'Constant Contact' => 'Constant Contact',
                    'Go High Level' => 'Go High Level',
                    'MailChimp' => 'MailChimp',
                    'Zeffy' => 'Zeffy',
                ],
                'default_value' => false,
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 1,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'create_options' => 0,
                'save_options' => 0,
            ],
            [
                'key' => 'field_69b5b6c6fe884',
                'label' => 'Constant Contact',
                'name' => 'constant-contact',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_69b5b54f29383',
                            'operator' => '==',
                            'value' => 'Constant Contact',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'row',
                'sub_fields' => [
                    [
                        'key' => 'field_69b5b6c6fe885',
                        'label' => 'Client ID',
                        'name' => 'client_id',
                        'aria-label' => '',
                        'type' => 'password',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_69b5c69ed8589',
                        'label' => 'Client Secret',
                        'name' => 'client_secret',
                        'aria-label' => '',
                        'type' => 'password',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_69b5b6c6fe885',
                                    'operator' => '!=empty',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_69b5b6c6fe886',
                        'label' => 'List ID',
                        'name' => 'list',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_69b5b6c6fe885',
                                    'operator' => '!=empty',
                                ],
                                [
                                    'field' => 'field_69b5c69ed8589',
                                    'operator' => '!=empty',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                ],
            ],
            [
                'key' => 'field_69b5d528ed70b',
                'label' => 'Mailchimp',
                'name' => 'mailchimp',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_69b5b54f29383',
                            'operator' => '==',
                            'value' => 'MailChimp',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'row',
                'sub_fields' => [
                    [
                        'key' => 'field_69b5d528ed70c',
                        'label' => 'API Key',
                        'name' => 'api',
                        'aria-label' => '',
                        'type' => 'password',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_69b5d528ed70e',
                        'label' => 'List ID',
                        'name' => 'list',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => [
                            [
                                [
                                    'field' => 'field_69b5d528ed70c',
                                    'operator' => '!=empty',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                ],
            ],
        ];
    }

    function meza_get_conference_information_fields(): array
    {
        return [
            [
                'key' => 'field_688f802239c77',
                'label' => 'Date',
                'name' => 'event_date',
                'aria-label' => '',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'display_format' => 'F j, Y',
                'return_format' => 'F j, Y',
                'first_day' => 1,
                'default_to_current_date' => 0,
                'allow_in_bindings' => 0,
            ],
            [
                'key' => 'field_688f809439c78',
                'label' => 'Start Time',
                'name' => 'event_start_time',
                'aria-label' => '',
                'type' => 'time_picker',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'display_format' => 'g:i a',
                'return_format' => 'g:i a',
                'allow_in_bindings' => 0,
            ],
            [
                'key' => 'field_688f80fe66ecc',
                'label' => 'End Time',
                'name' => 'event_end_time',
                'aria-label' => '',
                'type' => 'time_picker',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'display_format' => 'g:i a',
                'return_format' => 'g:i a',
                'allow_in_bindings' => 0,
            ],
            [
                'key' => 'field_688f81259766f',
                'label' => 'Location',
                'name' => 'event_location',
                'aria-label' => '',
                'type' => 'google_map',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'center_lat' => '',
                'center_lng' => '',
                'zoom' => '',
                'height' => '',
                'allow_in_bindings' => 0,
            ],
        ];
    }

    function meza_get_conference_schedule_fields(): array
    {
        return [
            [
                'key' => 'field_69f04bae33353',
                'label' => 'Segments',
                'name' => 'event_schedule',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'row',
                'pagination' => 0,
                'min' => 1,
                'max' => 0,
                'collapsed' => 'field_69f04bfb33356',
                'button_label' => 'Add Segment',
                'rows_per_page' => 20,
                'sub_fields' => [
                    [
                        'key' => 'field_69f04bcc33354',
                        'label' => 'Start Time',
                        'name' => 'start_time',
                        'aria-label' => '',
                        'type' => 'time_picker',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'display_format' => 'g:i a',
                        'return_format' => 'g:i a',
                        'allow_in_bindings' => 0,
                        'parent_repeater' => 'field_69f04bae33353',
                    ],
                    [
                        'key' => 'field_69f04be833355',
                        'label' => 'End Time',
                        'name' => 'end_time',
                        'aria-label' => '',
                        'type' => 'time_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'display_format' => 'g:i a',
                        'return_format' => 'g:i a',
                        'allow_in_bindings' => 0,
                        'parent_repeater' => 'field_69f04bae33353',
                    ],
                    [
                        'key' => 'field_69f04bfb33356',
                        'label' => 'Segment',
                        'name' => 'segment',
                        'aria-label' => '',
                        'type' => 'relationship',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'post_type' => [
                            'segment',
                        ],
                        'post_status' => [
                            'publish',
                        ],
                        'taxonomy' => '',
                        'filters' => [
                            'search',
                        ],
                        'return_format' => 'id',
                        'min' => 1,
                        'max' => 1,
                        'allow_in_bindings' => 0,
                        'elements' => [
                            'featured_image',
                        ],
                        'bidirectional' => 0,
                        'bidirectional_target' => [],
                        'parent_repeater' => 'field_69f04bae33353',
                    ],
                ],
            ],
        ];
    }

    function meza_get_segment_fields(): array
    {
        return [
            [
                'key' => 'field_69f04ade6d1e4',
                'label' => 'Speakers',
                'name' => 'speakers',
                'aria-label' => '',
                'type' => 'relationship',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'post_type' => [
                    'profile',
                ],
                'post_status' => [
                    'publish',
                ],
                'taxonomy' => [
                    'profile-type:speaker',
                ],
                'filters' => [
                    'search',
                ],
                'return_format' => 'id',
                'min' => '',
                'max' => 1,
                'allow_in_bindings' => 0,
                'elements' => [
                    'featured_image',
                ],
                'bidirectional' => 0,
                'bidirectional_target' => [],
            ],
            [
                'key' => 'field_69f04ade6d1e7',
                'label' => 'Sponsors',
                'name' => 'sponsors',
                'aria-label' => '',
                'type' => 'relationship',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'post_type' => [
                    'organization',
                ],
                'post_status' => [
                    'publish',
                ],
                'taxonomy' => [
                    'organization-type:sponsor',
                ],
                'filters' => [
                    'search',
                ],
                'return_format' => 'id',
                'min' => '',
                'max' => 3,
                'allow_in_bindings' => 0,
                'elements' => [
                    'featured_image',
                ],
                'bidirectional' => 0,
                'bidirectional_target' => [],
            ],
        ];
    }

