<?php

    function meza_get_cta_post_type_definition(): array
    {
        return [
            'key' => 'post_type_697fe24b7fe3f',
            'title' => 'CTAs',
            'menu_order' => 0,
            'active' => true,
            'post_type' => 'cta',
            'advanced_configuration' => true,
            'import_source' => '',
            'import_date' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
            'labels' => [
                'name' => 'CTAs',
                'singular_name' => 'CTA',
                'menu_name' => 'CTAs',
                'all_items' => 'All CTAs',
                'edit_item' => 'Edit CTA',
                'view_item' => 'View CTA',
                'view_items' => 'View CTAs',
                'add_new_item' => 'Add New CTA',
                'add_new' => 'Add New CTA',
                'new_item' => 'New CTA',
                'parent_item_colon' => 'Parent CTA:',
                'search_items' => 'Search CTAs',
                'not_found' => 'No ctas found',
                'not_found_in_trash' => 'No ctas found in Trash',
                'archives' => 'CTA Archives',
                'attributes' => 'CTA Attributes',
                'featured_image' => '',
                'set_featured_image' => '',
                'remove_featured_image' => '',
                'use_featured_image' => '',
                'insert_into_item' => 'Insert into cta',
                'uploaded_to_this_item' => 'Uploaded to this cta',
                'filter_items_list' => 'Filter ctas list',
                'filter_by_date' => 'Filter ctas by date',
                'items_list_navigation' => 'CTAs list navigation',
                'items_list' => 'CTAs list',
                'item_published' => 'CTA published.',
                'item_published_privately' => 'CTA published privately.',
                'item_reverted_to_draft' => 'CTA reverted to draft.',
                'item_scheduled' => 'CTA scheduled.',
                'item_updated' => 'CTA updated.',
                'item_link' => 'CTA Link',
                'item_link_description' => 'A link to a cta.',
            ],
            'description' => 'Manage reusable calls to action used across the website for lead generation, contact prompts, and section-level conversions.',
            'public' => true,
            'hierarchical' => false,
            'exclude_from_search' => true,
            'publicly_queryable' => false,
            'show_ui' => true,
            'show_in_menu' => true,
            'admin_menu_parent' => '',
            'show_in_admin_bar' => true,
            'show_in_nav_menus' => false,
            'show_in_rest' => true,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Posts_Controller',
            'menu_position' => '',
            'menu_icon' => [
                'type' => 'dashicons',
                'value' => 'dashicons-share-alt2',
            ],
            'rename_capabilities' => false,
            'singular_capability_name' => 'post',
            'plural_capability_name' => 'posts',
            'supports' => [
                'title',
                'excerpt',
                'custom-fields',
            ],
            'taxonomies' => [
                'event-type',
            ],
            'has_archive' => false,
            'has_archive_slug' => '',
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'post_type_key',
            'query_var_name' => '',
            'can_export' => true,
            'delete_with_user' => false,
            'register_meta_box_cb' => '',
            'enter_title_here' => '',
        ];
    }

    function meza_get_review_post_type_definition(): array
    {
        return [
            'key' => 'post_type_697fdc6d18380',
            'title' => 'Reviews',
            'menu_order' => 0,
            'active' => true,
            'post_type' => 'review',
            'advanced_configuration' => true,
            'import_source' => '',
            'import_date' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
            'labels' => [
                'name' => 'Reviews',
                'singular_name' => 'Review',
                'menu_name' => 'Reviews',
                'all_items' => 'All Reviews',
                'edit_item' => 'Edit Review',
                'view_item' => 'View Review',
                'view_items' => 'View Reviews',
                'add_new_item' => 'Add New Review',
                'add_new' => 'Add New Review',
                'new_item' => 'New Review',
                'parent_item_colon' => 'Parent Review:',
                'search_items' => 'Search Reviews',
                'not_found' => 'No reviews found',
                'not_found_in_trash' => 'No reviews found in Trash',
                'archives' => 'Review Archives',
                'attributes' => 'Review Attributes',
                'featured_image' => '',
                'set_featured_image' => '',
                'remove_featured_image' => '',
                'use_featured_image' => '',
                'insert_into_item' => 'Insert into review',
                'uploaded_to_this_item' => 'Uploaded to this review',
                'filter_items_list' => 'Filter reviews list',
                'filter_by_date' => 'Filter reviews by date',
                'items_list_navigation' => 'Reviews list navigation',
                'items_list' => 'Reviews list',
                'item_published' => 'Review published.',
                'item_published_privately' => 'Review published privately.',
                'item_reverted_to_draft' => 'Review reverted to draft.',
                'item_scheduled' => 'Review scheduled.',
                'item_updated' => 'Review updated.',
                'item_link' => 'Review Link',
                'item_link_description' => 'A link to a review.',
            ],
            'description' => 'Manage review content used across the website to support trust, proof, and related marketing sections.',
            'public' => true,
            'hierarchical' => false,
            'exclude_from_search' => true,
            'publicly_queryable' => false,
            'show_ui' => true,
            'show_in_menu' => true,
            'admin_menu_parent' => '',
            'show_in_admin_bar' => true,
            'show_in_nav_menus' => false,
            'show_in_rest' => true,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Posts_Controller',
            'menu_position' => '',
            'menu_icon' => [
                'type' => 'dashicons',
                'value' => 'dashicons-star-half',
            ],
            'rename_capabilities' => false,
            'singular_capability_name' => 'post',
            'plural_capability_name' => 'posts',
            'supports' => [
                'title',
                'editor',
                'page-attributes',
                'custom-fields',
            ],
            'taxonomies' => '',
            'has_archive' => false,
            'has_archive_slug' => '',
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'post_type_key',
            'query_var_name' => '',
            'can_export' => true,
            'delete_with_user' => false,
            'register_meta_box_cb' => '',
            'enter_title_here' => '',
        ];
    }

    function meza_get_faq_post_type_definition(): array
    {
        return [
            'key' => 'post_type_697fdfac7eb87',
            'title' => 'FAQs',
            'menu_order' => 0,
            'active' => true,
            'post_type' => 'faq',
            'advanced_configuration' => true,
            'import_source' => '',
            'import_date' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
            'labels' => [
                'name' => 'FAQs',
                'singular_name' => 'FAQ',
                'menu_name' => 'FAQs',
                'all_items' => 'All FAQs',
                'edit_item' => 'Edit FAQ',
                'view_item' => 'View FAQ',
                'view_items' => 'View FAQs',
                'add_new_item' => 'Add New FAQ',
                'add_new' => 'Add New FAQ',
                'new_item' => 'New FAQ',
                'parent_item_colon' => 'Parent FAQ:',
                'search_items' => 'Search FAQs',
                'not_found' => 'No faqs found',
                'not_found_in_trash' => 'No faqs found in Trash',
                'archives' => 'FAQ Archives',
                'attributes' => 'FAQ Attributes',
                'featured_image' => '',
                'set_featured_image' => '',
                'remove_featured_image' => '',
                'use_featured_image' => '',
                'insert_into_item' => 'Insert into faq',
                'uploaded_to_this_item' => 'Uploaded to this faq',
                'filter_items_list' => 'Filter faqs list',
                'filter_by_date' => 'Filter faqs by date',
                'items_list_navigation' => 'FAQs list navigation',
                'items_list' => 'FAQs list',
                'item_published' => 'FAQ published.',
                'item_published_privately' => 'FAQ published privately.',
                'item_reverted_to_draft' => 'FAQ reverted to draft.',
                'item_scheduled' => 'FAQ scheduled.',
                'item_updated' => 'FAQ updated.',
                'item_link' => 'FAQ Link',
                'item_link_description' => 'A link to a faq.',
            ],
            'description' => 'Manage reusable frequently asked questions used across the website to support service, product, and informational content.',
            'public' => true,
            'hierarchical' => false,
            'exclude_from_search' => true,
            'publicly_queryable' => false,
            'show_ui' => true,
            'show_in_menu' => true,
            'admin_menu_parent' => '',
            'show_in_admin_bar' => true,
            'show_in_nav_menus' => false,
            'show_in_rest' => true,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Posts_Controller',
            'menu_position' => '',
            'menu_icon' => [
                'type' => 'dashicons',
                'value' => 'dashicons-info',
            ],
            'rename_capabilities' => false,
            'singular_capability_name' => 'post',
            'plural_capability_name' => 'posts',
            'supports' => [
                'title',
                'page-attributes',
                'custom-fields',
            ],
            'taxonomies' => '',
            'has_archive' => false,
            'has_archive_slug' => '',
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'post_type_key',
            'query_var_name' => '',
            'can_export' => true,
            'delete_with_user' => false,
            'register_meta_box_cb' => '',
            'enter_title_here' => '',
        ];
    }

    function meza_get_event_post_type_definition(): array
    {
        $events_are_indexable = function_exists('meza_are_events_indexable') && meza_are_events_indexable();

        return [
            'key' => 'post_type_6898f5f8d4a36',
            'title' => 'Events',
            'menu_order' => 0,
            'active' => true,
            'post_type' => 'event',
            'advanced_configuration' => true,
            'import_source' => '',
            'import_date' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
            'labels' => [
                'name' => 'Events',
                'singular_name' => 'Event',
                'menu_name' => 'Events',
                'all_items' => 'All Events',
                'edit_item' => 'Edit Event',
                'view_item' => 'View Event',
                'view_items' => 'View Events',
                'add_new_item' => 'Add New Event',
                'add_new' => 'Add New Event',
                'new_item' => 'New Event',
                'parent_item_colon' => 'Parent Event:',
                'search_items' => 'Search Events',
                'not_found' => 'No events found',
                'not_found_in_trash' => 'No events found in Trash',
                'archives' => 'Event Archives',
                'attributes' => 'Event Attributes',
                'featured_image' => '',
                'set_featured_image' => '',
                'remove_featured_image' => '',
                'use_featured_image' => '',
                'insert_into_item' => 'Insert into event',
                'uploaded_to_this_item' => 'Uploaded to this event',
                'filter_items_list' => 'Filter events list',
                'filter_by_date' => 'Filter events by date',
                'items_list_navigation' => 'Events list navigation',
                'items_list' => 'Events list',
                'item_published' => 'Event published.',
                'item_published_privately' => 'Event published privately.',
                'item_reverted_to_draft' => 'Event reverted to draft.',
                'item_scheduled' => 'Event scheduled.',
                'item_updated' => 'Event updated.',
                'item_link' => 'Event Link',
                'item_link_description' => 'A link to a event.',
            ],
            'description' => 'Manage concert and event content with scheduled dates and times, venue or virtual location details, media, CTA links, and related partners, sponsors, and speakers.',
            'public' => true,
            'hierarchical' => false,
            'exclude_from_search' => !$events_are_indexable,
            'publicly_queryable' => $events_are_indexable,
            'show_ui' => true,
            'show_in_menu' => true,
            'admin_menu_parent' => '',
            'show_in_admin_bar' => true,
            'show_in_nav_menus' => $events_are_indexable,
            'show_in_rest' => true,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Posts_Controller',
            'menu_position' => '',
            'menu_icon' => [
                'type' => 'dashicons',
                'value' => 'dashicons-calendar-alt',
            ],
            'rename_capabilities' => false,
            'singular_capability_name' => 'post',
            'plural_capability_name' => 'posts',
            'supports' => [
                'title',
                'thumbnail',
                'custom-fields',
            ],
            'taxonomies' => '',
            'has_archive' => false,
            'has_archive_slug' => '',
            'rewrite' => [
                'permalink_rewrite' => $events_are_indexable ? 'permalink' : 'no_permalink',
            ],
            'query_var' => 'post_type_key',
            'query_var_name' => '',
            'can_export' => true,
            'delete_with_user' => false,
            'register_meta_box_cb' => '',
            'enter_title_here' => '',
        ];
    }

    function meza_get_certification_post_type_definition(): array
    {
        return [
            'key' => 'post_type_6913c88213321',
            'title' => 'Certifications',
            'menu_order' => 0,
            'active' => true,
            'post_type' => 'certification',
            'advanced_configuration' => true,
            'import_source' => '',
            'import_date' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
            'labels' => [
                'name' => 'Certifications',
                'singular_name' => 'Certification',
                'menu_name' => 'Certifications',
                'all_items' => 'All Certifications',
                'edit_item' => 'Edit Certification',
                'view_item' => 'View Certification',
                'view_items' => 'View Certifications',
                'add_new_item' => 'Add New Certification',
                'add_new' => 'Add New Certification',
                'new_item' => 'New Certification',
                'parent_item_colon' => 'Parent Certification:',
                'search_items' => 'Search Certifications',
                'not_found' => 'No certifications found',
                'not_found_in_trash' => 'No certifications found in Trash',
                'archives' => 'Certification Archives',
                'attributes' => 'Certification Attributes',
                'featured_image' => '',
                'set_featured_image' => '',
                'remove_featured_image' => '',
                'use_featured_image' => '',
                'insert_into_item' => 'Insert into certification',
                'uploaded_to_this_item' => 'Uploaded to this certification',
                'filter_items_list' => 'Filter certifications list',
                'filter_by_date' => 'Filter certifications by date',
                'items_list_navigation' => 'Certifications list navigation',
                'items_list' => 'Certifications list',
                'item_published' => 'Certification published.',
                'item_published_privately' => 'Certification published privately.',
                'item_reverted_to_draft' => 'Certification reverted to draft.',
                'item_scheduled' => 'Certification scheduled.',
                'item_updated' => 'Certification updated.',
                'item_link' => 'Certification Link',
                'item_link_description' => 'A link to a certification.',
            ],
            'description' => 'Manage certifications, accreditations, and trust badges used to highlight credibility with logos, short summaries, and outbound links.',
            'public' => true,
            'hierarchical' => false,
            'exclude_from_search' => true,
            'publicly_queryable' => false,
            'show_ui' => true,
            'show_in_menu' => true,
            'admin_menu_parent' => '',
            'show_in_admin_bar' => true,
            'show_in_nav_menus' => false,
            'show_in_rest' => true,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Posts_Controller',
            'menu_position' => '',
            'menu_icon' => [
                'type' => 'dashicons',
                'value' => 'dashicons-awards',
            ],
            'rename_capabilities' => false,
            'singular_capability_name' => 'post',
            'plural_capability_name' => 'posts',
            'supports' => [
                'title',
                'editor',
                'excerpt',
                'page-attributes',
                'thumbnail',
                'custom-fields',
            ],
            'taxonomies' => '',
            'has_archive' => false,
            'has_archive_slug' => '',
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'post_type_key',
            'query_var_name' => '',
            'can_export' => true,
            'delete_with_user' => false,
            'register_meta_box_cb' => '',
            'enter_title_here' => '',
        ];
    }

    function meza_get_organization_post_type_definition(): array
    {
        return [
            'key' => 'post_type_meza_organization',
            'title' => 'Organizations',
            'menu_order' => 0,
            'active' => true,
            'post_type' => 'organization',
            'advanced_configuration' => true,
            'import_source' => '',
            'import_date' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
            'labels' => [
                'name' => 'Organizations',
                'singular_name' => 'Organization',
                'menu_name' => 'Organizations',
                'all_items' => 'All Organizations',
                'edit_item' => 'Edit Organization',
                'view_item' => 'View Organization',
                'view_items' => 'View Organizations',
                'add_new_item' => 'Add New Organization',
                'add_new' => 'Add New Organization',
                'new_item' => 'New Organization',
                'parent_item_colon' => 'Parent Organization:',
                'search_items' => 'Search Organizations',
                'not_found' => 'No organizations found',
                'not_found_in_trash' => 'No organizations found in Trash',
                'archives' => 'Organization Archives',
                'attributes' => 'Organization Attributes',
                'featured_image' => '',
                'set_featured_image' => '',
                'remove_featured_image' => '',
                'use_featured_image' => '',
                'insert_into_item' => 'Insert into organization',
                'uploaded_to_this_item' => 'Uploaded to this organization',
                'filter_items_list' => 'Filter organizations list',
                'filter_by_date' => 'Filter organizations by date',
                'items_list_navigation' => 'Organizations list navigation',
                'items_list' => 'Organizations list',
                'item_published' => 'Organization published.',
                'item_published_privately' => 'Organization published privately.',
                'item_reverted_to_draft' => 'Organization reverted to draft.',
                'item_scheduled' => 'Organization scheduled.',
                'item_updated' => 'Organization updated.',
                'item_link' => 'Organization Link',
                'item_link_description' => 'A link to an organization.',
            ],
            'description' => 'Manage organizations used as venues, partners, sponsors, and other related groups across the website.',
            'public' => true,
            'hierarchical' => false,
            'exclude_from_search' => true,
            'publicly_queryable' => false,
            'show_ui' => true,
            'show_in_menu' => true,
            'admin_menu_parent' => '',
            'show_in_admin_bar' => true,
            'show_in_nav_menus' => false,
            'show_in_rest' => true,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Posts_Controller',
            'menu_position' => '',
            'menu_icon' => [
                'type' => 'dashicons',
                'value' => 'dashicons-admin-multisite',
            ],
            'rename_capabilities' => false,
            'singular_capability_name' => 'post',
            'plural_capability_name' => 'posts',
            'supports' => [
                'title',
                'excerpt',
                'page-attributes',
                'thumbnail',
                'custom-fields',
            ],
            'taxonomies' => '',
            'has_archive' => false,
            'has_archive_slug' => '',
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'post_type_key',
            'query_var_name' => '',
            'can_export' => true,
            'delete_with_user' => false,
            'register_meta_box_cb' => '',
            'enter_title_here' => '',
        ];
    }

    function meza_get_profile_post_type_definition(): array
    {
        return [
            'key' => 'post_type_meza_profile',
            'title' => 'Profiles',
            'menu_order' => 0,
            'active' => true,
            'post_type' => 'profile',
            'advanced_configuration' => true,
            'import_source' => '',
            'import_date' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
            'labels' => [
                'name' => 'Profiles',
                'singular_name' => 'Profile',
                'menu_name' => 'Profiles',
                'all_items' => 'All Profiles',
                'edit_item' => 'Edit Profile',
                'view_item' => 'View Profile',
                'view_items' => 'View Profiles',
                'add_new_item' => 'Add New Profile',
                'add_new' => 'Add New Profile',
                'new_item' => 'New Profile',
                'parent_item_colon' => 'Parent Profile:',
                'search_items' => 'Search Profiles',
                'not_found' => 'No profiles found',
                'not_found_in_trash' => 'No profiles found in Trash',
                'archives' => 'Profile Archives',
                'attributes' => 'Profile Attributes',
                'featured_image' => 'Serious Photo',
                'set_featured_image' => 'Set Serious Photo',
                'remove_featured_image' => 'Remove Serious Photo',
                'use_featured_image' => 'Use as Serious Photo',
                'insert_into_item' => 'Insert into profile',
                'uploaded_to_this_item' => 'Uploaded to this profile',
                'filter_items_list' => 'Filter profiles list',
                'filter_by_date' => 'Filter profiles by date',
                'items_list_navigation' => 'Profiles list navigation',
                'items_list' => 'Profiles list',
                'item_published' => 'Profile published.',
                'item_published_privately' => 'Profile published privately.',
                'item_reverted_to_draft' => 'Profile reverted to draft.',
                'item_scheduled' => 'Profile scheduled.',
                'item_updated' => 'Profile updated.',
                'item_link' => 'Profile Link',
                'item_link_description' => 'A link to a profile.',
            ],
            'description' => 'Manage people-related content such as staff, speakers, donors, and other profiles used across the website.',
            'public' => true,
            'hierarchical' => false,
            'exclude_from_search' => true,
            'publicly_queryable' => false,
            'show_ui' => true,
            'show_in_menu' => true,
            'admin_menu_parent' => '',
            'show_in_admin_bar' => true,
            'show_in_nav_menus' => false,
            'show_in_rest' => true,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Posts_Controller',
            'menu_position' => '',
            'menu_icon' => [
                'type' => 'dashicons',
                'value' => 'dashicons-id-alt',
            ],
            'rename_capabilities' => false,
            'singular_capability_name' => 'post',
            'plural_capability_name' => 'posts',
            'supports' => [
                'title',
                'excerpt',
                'page-attributes',
                'thumbnail',
                'custom-fields',
            ],
            'taxonomies' => '',
            'has_archive' => false,
            'has_archive_slug' => '',
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'post_type_key',
            'query_var_name' => '',
            'can_export' => true,
            'delete_with_user' => false,
            'register_meta_box_cb' => '',
            'enter_title_here' => '',
        ];
    }

    function meza_get_organization_type_taxonomy_definition(): array
    {
        return [
            'key' => 'taxonomy_68f8f72af1626',
            'title' => 'Organization Types',
            'menu_order' => 0,
            'active' => true,
            'taxonomy' => 'organization-type',
            'object_type' => [
                'organization',
            ],
            'advanced_configuration' => 1,
            'import_source' => '',
            'import_date' => '',
            'labels' => [
                'name' => 'Organization Types',
                'singular_name' => 'Organization Type',
                'menu_name' => 'Organization Types',
                'all_items' => 'All Organization Types',
                'edit_item' => 'Edit Organization Type',
                'view_item' => 'View Organization Type',
                'update_item' => 'Update Organization Type',
                'add_new_item' => 'Add New Organization Type',
                'new_item_name' => 'New Organization Type Name',
                'parent_item' => '',
                'parent_item_colon' => '',
                'search_items' => 'Search Organization Types',
                'most_used' => '',
                'not_found' => 'No organization types found',
                'no_terms' => 'No organization types',
                'name_field_description' => '',
                'slug_field_description' => '',
                'parent_field_description' => '',
                'desc_field_description' => '',
                'filter_by_item' => '',
                'items_list_navigation' => 'Organization Types list navigation',
                'items_list' => 'Organization Types list',
                'back_to_items' => '← Go to organization types',
                'item_link' => 'Organization Type Link',
                'item_link_description' => 'A link to a organization type',
            ],
            'description' => 'Organize organizations by their role on the site, such as partners, sponsors, venues, and sponsor tiers used in event and sponsorship displays.',
            'capabilities' => [
                'manage_terms' => 'manage_categories',
                'edit_terms' => 'manage_categories',
                'delete_terms' => 'manage_categories',
                'assign_terms' => 'edit_posts',
            ],
            'public' => 1,
            'publicly_queryable' => 0,
            'hierarchical' => 1,
            'show_ui' => 1,
            'show_in_menu' => 1,
            'show_in_nav_menus' => 0,
            'show_in_rest' => 1,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Terms_Controller',
            'show_tagcloud' => 0,
            'show_in_quick_edit' => 1,
            'show_admin_column' => 1,
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'taxonomy_key',
            'query_var_name' => '',
            'default_term' => [
                'default_term_enabled' => '0',
            ],
            'sort' => 0,
            'meta_box' => 'default',
            'meta_box_cb' => '',
            'meta_box_sanitize_cb' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
        ];
    }

    function meza_get_profile_type_taxonomy_definition(): array
    {
        return [
            'key' => 'taxonomy_68f8d8949a84a',
            'title' => 'Profile Types',
            'menu_order' => 0,
            'active' => true,
            'taxonomy' => 'profile-type',
            'object_type' => [
                'profile',
            ],
            'advanced_configuration' => 1,
            'import_source' => '',
            'import_date' => '',
            'labels' => [
                'name' => 'Profile Types',
                'singular_name' => 'Profile Type',
                'menu_name' => 'Profile Types',
                'all_items' => 'All Profile Types',
                'edit_item' => 'Edit Profile Type',
                'view_item' => 'View Profile Type',
                'update_item' => 'Update Profile Type',
                'add_new_item' => 'Add New Profile Type',
                'new_item_name' => 'New Profile Type Name',
                'parent_item' => '',
                'parent_item_colon' => '',
                'search_items' => 'Search Profile Types',
                'most_used' => '',
                'not_found' => 'No profile types found',
                'no_terms' => 'No profile types',
                'name_field_description' => '',
                'slug_field_description' => '',
                'parent_field_description' => '',
                'desc_field_description' => '',
                'filter_by_item' => '',
                'items_list_navigation' => 'Profile Types list navigation',
                'items_list' => 'Profile Types list',
                'back_to_items' => '← Go to profile types',
                'item_link' => 'Profile Type Link',
                'item_link_description' => 'A link to a profile type',
            ],
            'description' => 'Organize profiles by role or group, such as choir sections, leadership, board positions, speakers, donors, and instrument-based categories.',
            'capabilities' => [
                'manage_terms' => 'manage_categories',
                'edit_terms' => 'manage_categories',
                'delete_terms' => 'manage_categories',
                'assign_terms' => 'edit_posts',
            ],
            'public' => 1,
            'publicly_queryable' => 0,
            'hierarchical' => 1,
            'show_ui' => 1,
            'show_in_menu' => 1,
            'show_in_nav_menus' => 0,
            'show_in_rest' => 1,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Terms_Controller',
            'show_tagcloud' => 0,
            'show_in_quick_edit' => 1,
            'show_admin_column' => 1,
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'taxonomy_key',
            'query_var_name' => '',
            'default_term' => [
                'default_term_enabled' => '0',
            ],
            'sort' => 0,
            'meta_box' => 'default',
            'meta_box_cb' => '',
            'meta_box_sanitize_cb' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
        ];
    }

    function meza_get_locality_taxonomy_definition(): array
    {
        $localities_are_indexable = function_exists('meza_are_localities_indexable') && meza_are_localities_indexable();
        $object_types = [
            'review',
            'organization',
        ];

        if (function_exists('meza_are_services_enabled') && meza_are_services_enabled()) {
            array_unshift($object_types, 'service');
        }

        return [
            'key' => 'taxonomy_66b426000102',
            'title' => 'Localities',
            'menu_order' => 0,
            'active' => true,
            'taxonomy' => 'locality',
            'object_type' => $object_types,
            'advanced_configuration' => 1,
            'import_source' => '',
            'import_date' => '',
            'labels' => [
                'name' => 'Localities',
                'singular_name' => 'Locality',
                'menu_name' => 'Localities',
                'add_new_item' => 'Add New Locality',
            ],
            'description' => 'Organize content by service area or location so entries can be grouped and referenced geographically.',
            'capabilities' => [
                'manage_terms' => 'manage_categories',
                'edit_terms' => 'manage_categories',
                'delete_terms' => 'manage_categories',
                'assign_terms' => 'edit_posts',
            ],
            'public' => 1,
            'publicly_queryable' => $localities_are_indexable ? 1 : 0,
            'hierarchical' => 1,
            'show_ui' => 1,
            'show_in_menu' => 1,
            'show_in_nav_menus' => $localities_are_indexable ? 1 : 0,
            'show_in_rest' => 1,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Terms_Controller',
            'show_tagcloud' => $localities_are_indexable ? 1 : 0,
            'show_in_quick_edit' => 1,
            'show_admin_column' => 1,
            'rewrite' => $localities_are_indexable
                ? [
                    'permalink_rewrite' => 'taxonomy_key',
                    'with_front' => '1',
                    'rewrite_hierarchical' => '1',
                ]
                : [
                    'permalink_rewrite' => 'no_permalink',
                ],
            'query_var' => 'post_type_key',
            'query_var_name' => '',
            'default_term' => [
                'default_term_enabled' => '1',
                'name' => 'Fredericksburg, Virginia',
                'slug' => 'fredericksburg-virginia',
            ],
            'sort' => 0,
            'meta_box' => 'default',
            'meta_box_cb' => '',
            'meta_box_sanitize_cb' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
        ];
    }

    function meza_get_service_category_taxonomy_definition(): array
    {
        return [
            'key' => 'taxonomy_69f3aa4870280',
            'title' => 'Service Categories',
            'menu_order' => 0,
            'active' => true,
            'taxonomy' => 'service-category',
            'object_type' => [
                'service',
            ],
            'advanced_configuration' => 1,
            'import_source' => '',
            'import_date' => '',
            'labels' => [
                'name' => 'Service Categories',
                'singular_name' => 'Service Category',
                'menu_name' => 'Service Categories',
                'all_items' => 'All Service Categories',
                'edit_item' => 'Edit Service Category',
                'view_item' => 'View Service Category',
                'update_item' => 'Update Service Category',
                'add_new_item' => 'Add New Service Category',
                'new_item_name' => 'New Service Category Name',
                'search_items' => 'Search Service Categories',
                'popular_items' => 'Popular Service Categories',
                'separate_items_with_commas' => 'Separate service categories with commas',
                'add_or_remove_items' => 'Add or remove service categories',
                'choose_from_most_used' => 'Choose from the most used service categories',
                'most_used' => '',
                'not_found' => 'No service categories found',
                'no_terms' => 'No service categories',
                'name_field_description' => '',
                'slug_field_description' => '',
                'desc_field_description' => '',
                'items_list_navigation' => 'Service Categories list navigation',
                'items_list' => 'Service Categories list',
                'back_to_items' => '← Go to service categories',
                'item_link' => 'Service Category Link',
                'item_link_description' => 'A link to a service category',
            ],
            'description' => 'Organize service content into internal service categories for admin structure, filtering, and related grouping.',
            'capabilities' => [
                'manage_terms' => 'manage_categories',
                'edit_terms' => 'manage_categories',
                'delete_terms' => 'manage_categories',
                'assign_terms' => 'edit_posts',
            ],
            'public' => 1,
            'publicly_queryable' => 0,
            'hierarchical' => 0,
            'show_ui' => 1,
            'show_in_menu' => 1,
            'show_in_nav_menus' => 0,
            'show_in_rest' => 1,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Terms_Controller',
            'show_tagcloud' => 1,
            'show_in_quick_edit' => 1,
            'show_admin_column' => 1,
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'taxonomy_key',
            'query_var_name' => '',
            'default_term' => [
                'default_term_enabled' => '0',
            ],
            'sort' => 0,
            'meta_box' => 'default',
            'meta_box_cb' => '',
            'meta_box_sanitize_cb' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
        ];
    }

    function meza_get_topic_taxonomy_definition(): array
    {
        $topics_are_indexable = function_exists('meza_are_topics_indexable') && meza_are_topics_indexable();

        return [
            'key' => 'taxonomy_meza_topic',
            'title' => 'Topics',
            'menu_order' => 0,
            'active' => true,
            'taxonomy' => 'topic',
            'object_type' => [
                'event',
                'post',
            ],
            'advanced_configuration' => 1,
            'import_source' => '',
            'import_date' => '',
            'labels' => [
                'name' => 'Topics',
                'singular_name' => 'Topic',
                'menu_name' => 'Topics',
                'all_items' => 'All Topics',
                'edit_item' => 'Edit Topic',
                'view_item' => 'View Topic',
                'update_item' => 'Update Topic',
                'add_new_item' => 'Add New Topic',
                'new_item_name' => 'New Topic Name',
                'search_items' => 'Search Topics',
                'popular_items' => 'Popular Topics',
                'separate_items_with_commas' => 'Separate topics with commas',
                'add_or_remove_items' => 'Add or remove topics',
                'choose_from_most_used' => 'Choose from the most used topics',
                'most_used' => '',
                'not_found' => 'No topics found',
                'no_terms' => 'No topics',
                'name_field_description' => '',
                'slug_field_description' => '',
                'desc_field_description' => '',
                'items_list_navigation' => 'Topics list navigation',
                'items_list' => 'Topics list',
                'back_to_items' => '← Go to topics',
                'item_link' => 'Topic Link',
                'item_link_description' => 'A link to a topic',
            ],
            'description' => 'Organize posts and events by subject matter, program theme, or discussion area so related content can be grouped and filtered together.',
            'capabilities' => [
                'manage_terms' => 'manage_categories',
                'edit_terms' => 'manage_categories',
                'delete_terms' => 'manage_categories',
                'assign_terms' => 'edit_posts',
            ],
            'public' => 1,
            'publicly_queryable' => $topics_are_indexable ? 1 : 0,
            'hierarchical' => 0,
            'show_ui' => 1,
            'show_in_menu' => 1,
            'show_in_nav_menus' => $topics_are_indexable ? 1 : 0,
            'show_in_rest' => 1,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Terms_Controller',
            'show_tagcloud' => $topics_are_indexable ? 1 : 0,
            'show_in_quick_edit' => 1,
            'show_admin_column' => 1,
            'rewrite' => [
                'permalink_rewrite' => $topics_are_indexable ? 'permalink' : 'no_permalink',
            ],
            'query_var' => 'taxonomy_key',
            'query_var_name' => '',
            'default_term' => [
                'default_term_enabled' => '0',
            ],
            'sort' => 0,
            'meta_box' => 'default',
            'meta_box_cb' => '',
            'meta_box_sanitize_cb' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
        ];
    }

    function meza_get_event_type_taxonomy_definition(): array
    {
        return [
            'key' => 'taxonomy_6a0a4f1de9f01',
            'title' => 'Event Types',
            'menu_order' => 0,
            'active' => true,
            'taxonomy' => 'event-type',
            'object_type' => [
                'event',
            ],
            'advanced_configuration' => 1,
            'import_source' => '',
            'import_date' => '',
            'labels' => [
                'name' => 'Event Types',
                'singular_name' => 'Event Type',
                'menu_name' => 'Event Types',
                'all_items' => 'All Event Types',
                'edit_item' => 'Edit Event Type',
                'view_item' => 'View Event Type',
                'update_item' => 'Update Event Type',
                'add_new_item' => 'Add New Event Type',
                'new_item_name' => 'New Event Type Name',
                'parent_item' => '',
                'parent_item_colon' => '',
                'search_items' => 'Search Event Types',
                'most_used' => '',
                'not_found' => 'No event types found',
                'no_terms' => 'No event types',
                'name_field_description' => '',
                'slug_field_description' => '',
                'parent_field_description' => '',
                'desc_field_description' => '',
                'filter_by_item' => '',
                'items_list_navigation' => 'Event Types list navigation',
                'items_list' => 'Event Types list',
                'back_to_items' => '← Go to event types',
                'item_link' => 'Event Type Link',
                'item_link_description' => 'A link to an event type',
            ],
            'description' => 'Organize events by format or program category, such as concerts and similar event groupings, to support filtering, seasonal presentation, and admin organization.',
            'capabilities' => [
                'manage_terms' => 'manage_categories',
                'edit_terms' => 'manage_categories',
                'delete_terms' => 'manage_categories',
                'assign_terms' => 'edit_posts',
            ],
            'public' => 1,
            'publicly_queryable' => 0,
            'hierarchical' => 1,
            'show_ui' => 1,
            'show_in_menu' => 1,
            'show_in_nav_menus' => 0,
            'show_in_rest' => 1,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Terms_Controller',
            'show_tagcloud' => 0,
            'show_in_quick_edit' => 1,
            'show_admin_column' => 1,
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'taxonomy_key',
            'query_var_name' => '',
            'default_term' => [
                'default_term_enabled' => '0',
            ],
            'sort' => 0,
            'meta_box' => 'default',
            'meta_box_cb' => '',
            'meta_box_sanitize_cb' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
        ];
    }

    function meza_get_service_post_type_definition(): array
    {
        $services_are_indexable = function_exists('meza_are_services_indexable') && meza_are_services_indexable();
        $taxonomies = [
            'service-category',
        ];

        if (function_exists('meza_are_localities_enabled') && meza_are_localities_enabled()) {
            array_unshift($taxonomies, 'locality');
        }

        return [
            'key' => 'post_type_66b426000001',
            'title' => 'Services',
            'menu_order' => 0,
            'active' => true,
            'post_type' => 'service',
            'advanced_configuration' => true,
            'import_source' => '',
            'import_date' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
            'labels' => [
                'name' => 'Services',
                'singular_name' => 'Service',
                'menu_name' => 'Services',
                'all_items' => 'All Services',
                'edit_item' => 'Edit Service',
                'view_item' => 'View Service',
                'view_items' => 'View Services',
                'add_new_item' => 'Add New Service',
                'add_new' => 'Add New Service',
                'new_item' => 'New Service',
                'parent_item_colon' => '',
                'search_items' => 'Search Services',
                'not_found' => 'No services found',
                'not_found_in_trash' => 'No services found in Trash',
                'archives' => '',
                'attributes' => '',
                'featured_image' => '',
                'set_featured_image' => '',
                'remove_featured_image' => '',
                'use_featured_image' => '',
                'insert_into_item' => '',
                'uploaded_to_this_item' => '',
                'filter_items_list' => '',
                'filter_by_date' => '',
                'items_list_navigation' => '',
                'items_list' => '',
                'item_published' => '',
                'item_published_privately' => '',
                'item_reverted_to_draft' => '',
                'item_scheduled' => '',
                'item_updated' => '',
                'item_link' => '',
                'item_link_description' => '',
            ],
            'description' => 'Manage service content for the site\'s core offerings, including overview pages and supporting service-specific information.',
            'public' => true,
            'hierarchical' => true,
            'exclude_from_search' => !$services_are_indexable,
            'publicly_queryable' => $services_are_indexable,
            'show_ui' => true,
            'show_in_menu' => true,
            'show_in_admin_bar' => true,
            'show_in_nav_menus' => $services_are_indexable,
            'show_in_rest' => true,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Posts_Controller',
            'menu_position' => '',
            'menu_icon' => [
                'type' => 'dashicons',
                'value' => 'dashicons-hammer',
            ],
            'rename_capabilities' => false,
            'singular_capability_name' => 'post',
            'plural_capability_name' => 'posts',
            'supports' => [
                'title',
                'thumbnail',
                'custom-fields',
                'excerpt',
                'page-attributes',
            ],
            'taxonomies' => $taxonomies,
            'has_archive' => false,
            'has_archive_slug' => '',
            'rewrite' => $services_are_indexable
                ? [
                    'permalink_rewrite' => 'post_type_key',
                    'with_front' => '1',
                    'feeds' => '0',
                    'pages' => '1',
                ]
                : [
                    'permalink_rewrite' => 'no_permalink',
                ],
            'query_var' => 'post_type_key',
            'query_var_name' => '',
            'can_export' => true,
            'delete_with_user' => false,
            'register_meta_box_cb' => '',
            'enter_title_here' => '',
        ];
    }
