<?php

    function meza_get_cta_post_type_definition(): array
    {
        return [
            'key' => 'post_type_697fe24b7fe3f',
            'title' => 'CTAs',
            'menu_order' => 0,
            'active' => true,
            'post_type' => 'cta',
            'advanced_configuration' => true,
            'import_source' => '',
            'import_date' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
            'labels' => [
                'name' => 'CTAs',
                'singular_name' => 'CTA',
                'menu_name' => 'CTAs',
                'all_items' => 'All CTAs',
                'edit_item' => 'Edit CTA',
                'view_item' => 'View CTA',
                'view_items' => 'View CTAs',
                'add_new_item' => 'Add New CTA',
                'add_new' => 'Add New CTA',
                'new_item' => 'New CTA',
                'parent_item_colon' => 'Parent CTA:',
                'search_items' => 'Search CTAs',
                'not_found' => 'No ctas found',
                'not_found_in_trash' => 'No ctas found in Trash',
                'archives' => 'CTA Archives',
                'attributes' => 'CTA Attributes',
                'featured_image' => '',
                'set_featured_image' => '',
                'remove_featured_image' => '',
                'use_featured_image' => '',
                'insert_into_item' => 'Insert into cta',
                'uploaded_to_this_item' => 'Uploaded to this cta',
                'filter_items_list' => 'Filter ctas list',
                'filter_by_date' => 'Filter ctas by date',
                'items_list_navigation' => 'CTAs list navigation',
                'items_list' => 'CTAs list',
                'item_published' => 'CTA published.',
                'item_published_privately' => 'CTA published privately.',
                'item_reverted_to_draft' => 'CTA reverted to draft.',
                'item_scheduled' => 'CTA scheduled.',
                'item_updated' => 'CTA updated.',
                'item_link' => 'CTA Link',
                'item_link_description' => 'A link to a cta.',
            ],
            'description' => '',
            'public' => true,
            'hierarchical' => false,
            'exclude_from_search' => true,
            'publicly_queryable' => false,
            'show_ui' => true,
            'show_in_menu' => true,
            'admin_menu_parent' => '',
            'show_in_admin_bar' => true,
            'show_in_nav_menus' => false,
            'show_in_rest' => true,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Posts_Controller',
            'menu_position' => '',
            'menu_icon' => [
                'type' => 'dashicons',
                'value' => 'dashicons-share-alt2',
            ],
            'rename_capabilities' => false,
            'singular_capability_name' => 'post',
            'plural_capability_name' => 'posts',
            'supports' => [
                'title',
                'excerpt',
                'custom-fields',
            ],
            'taxonomies' => '',
            'has_archive' => false,
            'has_archive_slug' => '',
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'post_type_key',
            'query_var_name' => '',
            'can_export' => true,
            'delete_with_user' => false,
            'register_meta_box_cb' => '',
            'enter_title_here' => '',
        ];
    }

    function meza_get_review_post_type_definition(): array
    {
        return [
            'key' => 'post_type_697fdc6d18380',
            'title' => 'Reviews',
            'menu_order' => 0,
            'active' => true,
            'post_type' => 'review',
            'advanced_configuration' => true,
            'import_source' => '',
            'import_date' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
            'labels' => [
                'name' => 'Reviews',
                'singular_name' => 'Review',
                'menu_name' => 'Reviews',
                'all_items' => 'All Reviews',
                'edit_item' => 'Edit Review',
                'view_item' => 'View Review',
                'view_items' => 'View Reviews',
                'add_new_item' => 'Add New Review',
                'add_new' => 'Add New Review',
                'new_item' => 'New Review',
                'parent_item_colon' => 'Parent Review:',
                'search_items' => 'Search Reviews',
                'not_found' => 'No reviews found',
                'not_found_in_trash' => 'No reviews found in Trash',
                'archives' => 'Review Archives',
                'attributes' => 'Review Attributes',
                'featured_image' => '',
                'set_featured_image' => '',
                'remove_featured_image' => '',
                'use_featured_image' => '',
                'insert_into_item' => 'Insert into review',
                'uploaded_to_this_item' => 'Uploaded to this review',
                'filter_items_list' => 'Filter reviews list',
                'filter_by_date' => 'Filter reviews by date',
                'items_list_navigation' => 'Reviews list navigation',
                'items_list' => 'Reviews list',
                'item_published' => 'Review published.',
                'item_published_privately' => 'Review published privately.',
                'item_reverted_to_draft' => 'Review reverted to draft.',
                'item_scheduled' => 'Review scheduled.',
                'item_updated' => 'Review updated.',
                'item_link' => 'Review Link',
                'item_link_description' => 'A link to a review.',
            ],
            'description' => '',
            'public' => true,
            'hierarchical' => false,
            'exclude_from_search' => true,
            'publicly_queryable' => false,
            'show_ui' => true,
            'show_in_menu' => true,
            'admin_menu_parent' => '',
            'show_in_admin_bar' => true,
            'show_in_nav_menus' => false,
            'show_in_rest' => true,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Posts_Controller',
            'menu_position' => '',
            'menu_icon' => [
                'type' => 'dashicons',
                'value' => 'dashicons-star-half',
            ],
            'rename_capabilities' => false,
            'singular_capability_name' => 'post',
            'plural_capability_name' => 'posts',
            'supports' => [
                'title',
                'editor',
                'page-attributes',
                'custom-fields',
            ],
            'taxonomies' => '',
            'has_archive' => false,
            'has_archive_slug' => '',
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'post_type_key',
            'query_var_name' => '',
            'can_export' => true,
            'delete_with_user' => false,
            'register_meta_box_cb' => '',
            'enter_title_here' => '',
        ];
    }

    function meza_get_faq_post_type_definition(): array
    {
        return [
            'key' => 'post_type_697fdfac7eb87',
            'title' => 'FAQs',
            'menu_order' => 0,
            'active' => true,
            'post_type' => 'faq',
            'advanced_configuration' => true,
            'import_source' => '',
            'import_date' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
            'labels' => [
                'name' => 'FAQs',
                'singular_name' => 'FAQ',
                'menu_name' => 'FAQs',
                'all_items' => 'All FAQs',
                'edit_item' => 'Edit FAQ',
                'view_item' => 'View FAQ',
                'view_items' => 'View FAQs',
                'add_new_item' => 'Add New FAQ',
                'add_new' => 'Add New FAQ',
                'new_item' => 'New FAQ',
                'parent_item_colon' => 'Parent FAQ:',
                'search_items' => 'Search FAQs',
                'not_found' => 'No faqs found',
                'not_found_in_trash' => 'No faqs found in Trash',
                'archives' => 'FAQ Archives',
                'attributes' => 'FAQ Attributes',
                'featured_image' => '',
                'set_featured_image' => '',
                'remove_featured_image' => '',
                'use_featured_image' => '',
                'insert_into_item' => 'Insert into faq',
                'uploaded_to_this_item' => 'Uploaded to this faq',
                'filter_items_list' => 'Filter faqs list',
                'filter_by_date' => 'Filter faqs by date',
                'items_list_navigation' => 'FAQs list navigation',
                'items_list' => 'FAQs list',
                'item_published' => 'FAQ published.',
                'item_published_privately' => 'FAQ published privately.',
                'item_reverted_to_draft' => 'FAQ reverted to draft.',
                'item_scheduled' => 'FAQ scheduled.',
                'item_updated' => 'FAQ updated.',
                'item_link' => 'FAQ Link',
                'item_link_description' => 'A link to a faq.',
            ],
            'description' => '',
            'public' => true,
            'hierarchical' => false,
            'exclude_from_search' => true,
            'publicly_queryable' => false,
            'show_ui' => true,
            'show_in_menu' => true,
            'admin_menu_parent' => '',
            'show_in_admin_bar' => true,
            'show_in_nav_menus' => false,
            'show_in_rest' => true,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Posts_Controller',
            'menu_position' => '',
            'menu_icon' => [
                'type' => 'dashicons',
                'value' => 'dashicons-info',
            ],
            'rename_capabilities' => false,
            'singular_capability_name' => 'post',
            'plural_capability_name' => 'posts',
            'supports' => [
                'title',
                'page-attributes',
                'custom-fields',
            ],
            'taxonomies' => '',
            'has_archive' => false,
            'has_archive_slug' => '',
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'post_type_key',
            'query_var_name' => '',
            'can_export' => true,
            'delete_with_user' => false,
            'register_meta_box_cb' => '',
            'enter_title_here' => '',
        ];
    }

    function meza_get_sponsor_type_taxonomy_definition(): array
    {
        return [
            'key' => 'taxonomy_688f86716fff9',
            'title' => 'Sponsor Types',
            'menu_order' => 0,
            'active' => true,
            'taxonomy' => 'sponsor-type',
            'object_type' => [
                'organization',
            ],
            'advanced_configuration' => 1,
            'import_source' => '',
            'import_date' => '',
            'labels' => [
                'name' => 'Sponsor Types',
                'singular_name' => 'Sponsor Type',
                'menu_name' => 'Sponsor Types',
                'all_items' => 'All Sponsor Types',
                'edit_item' => 'Edit Sponsor Type',
                'view_item' => 'View Sponsor Type',
                'update_item' => 'Update Sponsor Type',
                'add_new_item' => 'Add New Sponsor Type',
                'new_item_name' => 'New Sponsor Type Name',
                'search_items' => 'Search Sponsor Types',
                'popular_items' => 'Popular Sponsor Types',
                'separate_items_with_commas' => 'Separate sponsor types with commas',
                'add_or_remove_items' => 'Add or remove sponsor types',
                'choose_from_most_used' => 'Choose from the most used sponsor types',
                'most_used' => '',
                'not_found' => 'No sponsor types found',
                'no_terms' => 'No sponsor types',
                'name_field_description' => '',
                'slug_field_description' => '',
                'desc_field_description' => '',
                'items_list_navigation' => 'Sponsor Types list navigation',
                'items_list' => 'Sponsor Types list',
                'back_to_items' => '← Go to sponsor types',
                'item_link' => 'Sponsor Type Link',
                'item_link_description' => 'A link to a sponsor type',
            ],
            'description' => '',
            'capabilities' => [
                'manage_terms' => 'manage_categories',
                'edit_terms' => 'manage_categories',
                'delete_terms' => 'manage_categories',
                'assign_terms' => 'edit_posts',
            ],
            'public' => 1,
            'publicly_queryable' => 0,
            'hierarchical' => 0,
            'show_ui' => 1,
            'show_in_menu' => 1,
            'show_in_nav_menus' => 0,
            'show_in_rest' => 1,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Terms_Controller',
            'show_tagcloud' => 0,
            'show_in_quick_edit' => 1,
            'show_admin_column' => 1,
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'taxonomy_key',
            'query_var_name' => '',
            'default_term' => [
                'default_term_enabled' => '0',
            ],
            'sort' => 0,
            'meta_box' => 'default',
            'meta_box_cb' => '',
            'meta_box_sanitize_cb' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
        ];
    }

    function meza_get_locality_taxonomy_definition(): array
    {
        return [
            'key' => 'taxonomy_66b426000102',
            'title' => 'Localities',
            'menu_order' => 0,
            'active' => true,
            'taxonomy' => 'locality',
            'object_type' => [
                'service',
                'review',
                'organization',
            ],
            'advanced_configuration' => 1,
            'import_source' => '',
            'import_date' => '',
            'labels' => [
                'name' => 'Localities',
                'singular_name' => 'Locality',
                'menu_name' => 'Localities',
                'add_new_item' => 'Add New Locality',
            ],
            'description' => '',
            'capabilities' => [
                'manage_terms' => 'manage_categories',
                'edit_terms' => 'manage_categories',
                'delete_terms' => 'manage_categories',
                'assign_terms' => 'edit_posts',
            ],
            'public' => 1,
            'publicly_queryable' => 1,
            'hierarchical' => 1,
            'show_ui' => 1,
            'show_in_menu' => 1,
            'show_in_nav_menus' => 1,
            'show_in_rest' => 1,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Terms_Controller',
            'show_tagcloud' => 1,
            'show_in_quick_edit' => 1,
            'show_admin_column' => 1,
            'rewrite' => [
                'permalink_rewrite' => 'taxonomy_key',
                'with_front' => '1',
                'rewrite_hierarchical' => '1',
            ],
            'query_var' => 'post_type_key',
            'query_var_name' => '',
            'default_term' => [
                'default_term_enabled' => '1',
                'name' => 'Fredericksburg, Virginia',
                'slug' => 'fredericksburg-virginia',
            ],
            'sort' => 0,
            'meta_box' => 'default',
            'meta_box_cb' => '',
            'meta_box_sanitize_cb' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
        ];
    }

    function meza_get_service_category_taxonomy_definition(): array
    {
        return [
            'key' => 'taxonomy_69f3aa4870280',
            'title' => 'Service Categories',
            'menu_order' => 0,
            'active' => true,
            'taxonomy' => 'service-category',
            'object_type' => [
                'service',
            ],
            'advanced_configuration' => 1,
            'import_source' => '',
            'import_date' => '',
            'labels' => [
                'name' => 'Service Categories',
                'singular_name' => 'Service Category',
                'menu_name' => 'Service Categories',
                'all_items' => 'All Service Categories',
                'edit_item' => 'Edit Service Category',
                'view_item' => 'View Service Category',
                'update_item' => 'Update Service Category',
                'add_new_item' => 'Add New Service Category',
                'new_item_name' => 'New Service Category Name',
                'search_items' => 'Search Service Categories',
                'popular_items' => 'Popular Service Categories',
                'separate_items_with_commas' => 'Separate service categories with commas',
                'add_or_remove_items' => 'Add or remove service categories',
                'choose_from_most_used' => 'Choose from the most used service categories',
                'most_used' => '',
                'not_found' => 'No service categories found',
                'no_terms' => 'No service categories',
                'name_field_description' => '',
                'slug_field_description' => '',
                'desc_field_description' => '',
                'items_list_navigation' => 'Service Categories list navigation',
                'items_list' => 'Service Categories list',
                'back_to_items' => '← Go to service categories',
                'item_link' => 'Service Category Link',
                'item_link_description' => 'A link to a service category',
            ],
            'description' => '',
            'capabilities' => [
                'manage_terms' => 'manage_categories',
                'edit_terms' => 'manage_categories',
                'delete_terms' => 'manage_categories',
                'assign_terms' => 'edit_posts',
            ],
            'public' => 1,
            'publicly_queryable' => 0,
            'hierarchical' => 0,
            'show_ui' => 1,
            'show_in_menu' => 1,
            'show_in_nav_menus' => 0,
            'show_in_rest' => 1,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Terms_Controller',
            'show_tagcloud' => 1,
            'show_in_quick_edit' => 1,
            'show_admin_column' => 1,
            'rewrite' => [
                'permalink_rewrite' => 'no_permalink',
            ],
            'query_var' => 'taxonomy_key',
            'query_var_name' => '',
            'default_term' => [
                'default_term_enabled' => '0',
            ],
            'sort' => 0,
            'meta_box' => 'default',
            'meta_box_cb' => '',
            'meta_box_sanitize_cb' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
        ];
    }

    function meza_get_service_post_type_definition(): array
    {
        return [
            'key' => 'post_type_66b426000001',
            'title' => 'Services',
            'menu_order' => 0,
            'active' => true,
            'post_type' => 'service',
            'advanced_configuration' => true,
            'import_source' => '',
            'import_date' => '',
            'allow_ai_access' => false,
            'ai_description' => '',
            'labels' => [
                'name' => 'Services',
                'singular_name' => 'Service',
                'menu_name' => 'Services',
                'all_items' => 'All Services',
                'edit_item' => 'Edit Service',
                'view_item' => 'View Service',
                'view_items' => 'View Services',
                'add_new_item' => 'Add New Service',
                'add_new' => 'Add New Service',
                'new_item' => 'New Service',
                'parent_item_colon' => '',
                'search_items' => 'Search Services',
                'not_found' => 'No services found',
                'not_found_in_trash' => 'No services found in Trash',
                'archives' => '',
                'attributes' => '',
                'featured_image' => '',
                'set_featured_image' => '',
                'remove_featured_image' => '',
                'use_featured_image' => '',
                'insert_into_item' => '',
                'uploaded_to_this_item' => '',
                'filter_items_list' => '',
                'filter_by_date' => '',
                'items_list_navigation' => '',
                'items_list' => '',
                'item_published' => '',
                'item_published_privately' => '',
                'item_reverted_to_draft' => '',
                'item_scheduled' => '',
                'item_updated' => '',
                'item_link' => '',
                'item_link_description' => '',
            ],
            'description' => '',
            'public' => true,
            'hierarchical' => true,
            'exclude_from_search' => false,
            'publicly_queryable' => true,
            'show_ui' => true,
            'show_in_menu' => true,
            'show_in_admin_bar' => true,
            'show_in_nav_menus' => true,
            'show_in_rest' => true,
            'rest_base' => '',
            'rest_namespace' => 'wp/v2',
            'rest_controller_class' => 'WP_REST_Posts_Controller',
            'menu_position' => '',
            'menu_icon' => [
                'type' => 'dashicons',
                'value' => 'dashicons-hammer',
            ],
            'rename_capabilities' => false,
            'singular_capability_name' => 'post',
            'plural_capability_name' => 'posts',
            'supports' => [
                'title',
                'thumbnail',
                'custom-fields',
                'excerpt',
                'page-attributes',
            ],
            'taxonomies' => [
                'locality',
                'service-category',
            ],
            'has_archive' => false,
            'has_archive_slug' => '',
            'rewrite' => [
                'permalink_rewrite' => 'post_type_key',
                'with_front' => '1',
                'feeds' => '0',
                'pages' => '1',
            ],
            'query_var' => 'post_type_key',
            'query_var_name' => '',
            'can_export' => true,
            'delete_with_user' => false,
            'register_meta_box_cb' => '',
            'enter_title_here' => '',
        ];
    }

